### ISSUE TITLE
Any estimation for Masks test vector expected responses availability?

### ISSUE THREAD

**Issue by gonzalocasado** [Wireless-Innovation-Forum/6-GHz-AFC#33]

**Comment by AEgbert** [comment]
Thanks for the question. The test vector expected responses are currently under active development by Wi-Fi Alliance and the Wireless Innovation Forum. Once they are officially released, we will add them to this repository, but I'm not able to comment on a time frame for that release.

If you would like to be notified of when the repository is updated with the expected response files, you may wish to use a GitHub file watching service ([such as this one](https://app.github-file-watcher.com/)) to monitor the [`masks`](https://github.com/Wireless-Innovation-Forum/6-GHz-AFC/tree/main/src/harness) directory of our repository.

I'll also leave this issue open for now and will provide an update here if and when one becomes available.

**Comment by AEgbert** [comment]
Wi-Fi Alliance has published a version of the expected responses for system testing (accessible [here](https://www.wi-fi.org/file/afc-specification-and-test-plans)). Please note that, along with this release, the SDI protocol version has been increased to v1.4. Currently, the test harness in this repository supports v1.3. We will wait to include the updated inquiries and masks in this repository until the harness also supports v1.4.

**Comment by gonzalocasado** [comment]
Appreciated the update.

Any ETA about when the test harness may support v1.4 and the expected responses?

**Comment by AEgbert** [comment]
Sorry for the delayed response. I don't have a more solid ETA for the official release aside from "soon." However, I have just uploaded a draft of the test harness modifications and the latest public expected responses from Wi-Fi Alliance to a development fork. You can preview the changes here: https://github.com/AEgbert/6-GHz-AFC/tree/SDI_v1.4

**Comment by AEgbert** [comment]
I'm expecting that the main branch of this repo will be updated by next Tuesday at the latest, using the changes from the linked fork above. I'll post a final update and close out this issue once that occurs.

**Comment by AEgbert** [comment]
The discussed changes have now been merged into the main branch of this repository via #35.
