### ISSUE TITLE
IBP 5-8 Masks Missing?

### ISSUE THREAD

**Issue by haroon-akhtar** [Wireless-Innovation-Forum/6-GHz-AFC#37]
Hello, during execution noticed that IBP 5,6,7,8 were skipped due to missing masks, also noticed that they were not in the masks folder. Was wondering if these masks are to be added for these tests soon? Thank you!

**Comment by AEgbert** [comment]
IBP.5-8 are designed to test international border protection with Mexico. While placeholders for these requests (with no device location) are included in Wi-Fi Alliance's SUT test vector document (and by extension, in this test harness), development of official test vectors is awaiting regulatory guidance on protection of the Mexico border. Until their completion or removal, the harness will skip these incomplete tests. For now, log messages related to these skipped tests can be safely ignored.

**Comment by haroon-akhtar** [comment]
Thank you for the clarification!
