### ISSUE TITLE
Discrepancy in FSP36 response mask PSD and EIRP values

### ISSUE THREAD

**Issue by sbasu07** [Wireless-Innovation-Forum/6-GHz-AFC#44]
Hi, 
For FSP 36 case my PSD values are matching with the response mask, but EIRP value is not matching for global operating class 134, channel 79.
For FSP 30 test case both PSD and EIRP values are matching with the response mask.
Seeing the inquiry messages, we can infer both the test vectors are exactly same except the indoor/outdoor deployment scenario, which accounts for the 20.5 dB (Building entry loss) difference in the PSD values.
@AEgbert , could you clarify how FSP36 PSD values (23 dBm/MHz) generate EIRP Value of (28.9 - 30.9 dBm) for global operating class 134, channel 79?
This is the excel sheet that shows FSP36 and FSP30 test vector PSD and EIRP (global class 134) values provided in response masks and my output values.
https://docs.google.com/spreadsheets/d/1PcpDMwvZEl04JMFB37XEAGMZPcNRrTGu/edit?usp=sharing&ouid=102576313353049347002&rtpof=true&sd=true

**Comment by AEgbert** [comment]
TS-1014 contains adjacent channel emission requirements (R0-AIP-04, R0-AIP-07, R2-AIP-03), in addition to in-band emission requirements.

Looking at the PSD values for FSP-36, I note a limit exists on 6211-6242 MHz, which falls within the adjacent channel range of GOC 134, CFI 79. While FSP-30 contains a limit on the same frequency range, it is not low enough to constrain the in-channel transmission.

**Comment by sbasu07** [comment]
Hi @AEgbert, thank your for your response. Could you clarify a little more about the adjacent channel calculation that is specified in 47 CFR 15.407(b)(7))?

"Power spectral density must be suppressed by 20 dB at 1 MHz outside of channel edge, by 28 dB at one channel bandwidth from the channel center, and by 40 dB at one- and one-half times the channel bandwidth away from channel center."

Q.1 Here, channel center is to be considered as 6226 MHz (center of 6211-6242 MHz) or 6185 MHz (center frequency of channel 47, GOC 134)?

Q.2. After getting PSD values at frequencies of channel edge (-15.3+20= 4.7dBm), 1 bandwidth (-15.3+28 = 12.7 dBm) and 1.5 bandwidth (-15.3+40 = 24.7 dBm) away from channel center, how should we calculate EIRP value for the whole channel (CFI 79, GOC 134)? 

Q.3 Another observation - same limiting PSD value is observed in response mask of test vector FSP33 (CFI 15, GOC 134). But the adjacent channel 47 does shows EIRP of full 36 dBm. How is this scenario different from FSP36 test case?

**Comment by AEgbert** [comment]
A.1: The channel center is the center of the device's main channel, not the incumbent channel or adjacent device channel. For this example, this would be the GOC 134, CFI 79 channel.

A.2: I would suggest working in the opposite direction. The regulations state:

>At frequencies between one megahertz outside an unlicensed device's channel edge and one channel bandwidth from the center of the channel, the limits must be linearly interpolated between 20 dB and 28 dB suppression, and at frequencies between one and one- and one-half times an unlicensed device's channel bandwidth, the limits must be linearly interpolated between 28 dB and 40 dB suppression.

In this example, the edge of the incumbent band closest to the unlicensed device is 6242 MHz. Linearly interpolating between suppression levels of 20dB at the channel edge and 28dB at one channel bandwidth from the center will give a suppression level for 6242 MHz between 20 and 28dB. This value can be used to relax the incumbent constraint (i.e., -15.3dBm/MHz + this value) to arrive at the in-band PSD limit.

A.3: In FSP-33, the limiting incumbent appears to exist at 5959-5990 MHz. This is farther away from the edge of GOC 134 CFI 47, and thus the device's adjacent channel suppression further limits the power transmitted in the incumbent's band. It appears that the greater suppression value is large enough that the full 36dBm EIRP can be transmitted in CFI 47.

**Comment by sbasu07** [comment]
Hi @AEgbert , 

> A.1: The channel center is the center of the device's main channel, not the incumbent channel or adjacent device channel. For this example, this would be the GOC 134, CFI 79 channel.

Is it not CFI 47, GOC 134 considered as the device's main channel? As the incumbent lies in 6211-6242 MHz and CFI 47, GOC 134 covers 6105-6265 MHz

> In this example, the edge of the incumbent band closest to the unlicensed device is 6242 MHz. Linearly interpolating between suppression levels of 20dB at the channel edge and 28dB at one channel bandwidth from the center will give a suppression level for 6242 MHz between 20 and 28dB. This value can be used to relax the incumbent constraint (i.e., -15.3dBm/MHz + this value) to arrive at the in-band PSD limit.

So, for this particular scenario in FSP36,
For 160 MHz, 
unlicensed device's channel edge = 6242 MHz, Suppression level at 6242 MHz is 20 dB.
one channel bandwidth (160 MHz) from the center of the main channel (6185 MHz) is = 6345 MHz. Suppression level at 6345 MHz is 28 dB.
Linearly interpolating this, we get 21.78 dB suppression at channel edge 6265 MHz. This gives EIRP =( -15.3 dBm/MHz + 10*log10(160) MHz + 21.7 ) = 28.5 dBm at CFI 79, GOC 134. This comes close to the range (28.9-30.9 dBm)

But for 80 MHz,
unlicensed device's channel edge = 6242 MHz, Suppression level at 6242 MHz is 20 dB.
one channel bandwidth (80 MHz) from the center of the main channel (6225MHz) is = 6305 MHz. Suppression level at 6305 MHz is 28 dB.
Linearly interpolating this, we get 22.92 dB suppression at channel edge 6265 MHz. This gives EIRP = ( -15.3 dBm/MHz + 10*log10(80) MHz + 22.92 ) = 26.6 dBm at CFI 71, GOC 133. This does not fall within range (28.2-30.2 dBm)

Similarly, it comes as 27.32 dBm for CFI 67, GOC 132, Where limit is (30.5-32.5 dBm). Could you let me know what am I missing here?

**Comment by AEgbert** [comment]
> >A.1: The channel center is the center of the device's main channel, not the incumbent channel or adjacent device channel. For this example, this would be the GOC 134, CFI 79 channel.
>
>Is it not CFI 47, GOC 134 considered as the device's main channel? As the incumbent lies in 6211-6242 MHz and CFI 47, GOC 134 covers 6105-6265 MHz

The question is on the maxEIRP value for GOC 134, CFI 79. This channel occupies 6265-6425 MHz, and its lower adjacent channel is 6105-6265 MHz. No incumbent limitations are listed as being within the channel itself (6265-6425 MHz), but the regulations and specifications state that adjacent channels must also be protected, and an incumbent limitation is listed within the lower adjacent channel (6211-6242 MHz within the adjacent 6105-6265 MHz channel).

The adjacent channel suppression values should be calculated with respect to CFI 79, as it is the channel for which a max EIRP value is being calculated, and it is the channel to which the suppression requirements are being applied. The frequencies at which the various suppression requirements (20, 28, and 40dB) are specified exist within the adjacent channel CFI 47, but they are defined with respect to CFI 79's frequencies (band edge, center - one channel width, center - 1.5 channel widths). The incumbent frequency specifies the index frequency to which the suppression value is interpolated.

**Comment by hollowopk** [comment]
@sbasu07 Hello, I am currently trying to derive the FSP30, and I have achieved the expected results in the frequency range of 5959-5990MHz. However, I am unable to calculate the correct results in the frequency range of 6211-6242MHz. If possible, I would appreciate it if I could refer to the intermediate results of your derivation regarding the maxpsd in the FSP30 for the 6211-6242MHz frequency range. Alternatively, could you please let me know which fixed service is causing this limitation? Thank you.
