### ISSUE TITLE
When unable to fetch daily data from FCC ULS, such as when FCC does not update the data on a particular day, should the AFC System continue to provide services?

### ISSUE THREAD

**Issue by hollowopk** [Wireless-Innovation-Forum/6-GHz-AFC#45]
There seems to be no mention of this in the document .

**Comment by AEgbert** [comment]
Hi @hollowopk,

I've checked with some others, and yes, AFC systems should continue to provide services based on "the most recent information on fixed service links" (from R1-AIP-02's reference to Paragraph 30 of [[n.3]](https://docs.fcc.gov/public/attachments/FCC-20-51A1_Rcd.pdf)), which would be the last available ULS download. While this connection is not immediately evident, we have confirmed this interpretation with the FCC.

**Comment by hollowopk** [comment]
@AEgbert thank you for clarifying
