### ISSUE TITLE
ULS Path data incomplete for AFCS.SIP.3

### ISSUE THREAD

**Issue by alexcpn** [Wireless-Innovation-Forum/6-GHz-AFC#47]
I am getting the following Incumbent for AFCS.SIP.3, ` (2986933, 'WQII545')` 

In LO.dat it has the following receiver locations (2,4,3) and a transmit location (1)

```
LO|2986933|||WQII545||F|R|4||||||||||2340.0|34|2|16.9|N|107|26|46.9|W||||||||||||||||NM3MAGDALENA||||||||
LO|2986933|||WQII545||F|T|1|||Near US-60 Mile Marker 67, on top of mountain SW of Hwy (Datil #89009)|DATIL|CATRON|NM||||2553.3|34|15|1.2|N|107|57|16.7|W|||||||||N||1005469|88.1|93.5|LTOWER||NM3SMITHBGLY||||||||
LO|2986933|||WQII545||F|R|2||||||||||2340.1|34|2|16.8|N|107|26|46.6|W||||||||||||||||MAGDALENA|||||||| 
LO|2986933|||WQII545||F|R|3||||||||||2326.5|34|18|26.1|N|108|35|41.1|W||||||||||||||||NM3 QUEMADO||||||||
```

However, in the Path file PA.dat, entries are there only for receiver location (4 and 3)

```
PA.DAT file
PA|2986933|||WQII545||3|1|3|3|2||Fixed Point-to-Point|N||N|WQII546|||||||
PA|2986933|||WQII545||4|1|4|4|1||Fixed Point-to-Point|N||N|WQII544|||||||
```

My code reference where this data is parsed to DB
```
Transmit path number Not found for (2986933, 'WQII545') and receiver_location_number=2 

//----------------------------------------------------------------------------------
SELECT * FROM location where         call_sign = 'WQII545' and unique_system_identifier=2986933               and location_class_code ='R'

"record_type","unique_system_identifier","uls_file_number","ebf_number","call_sign","location_action_performed","location_type_code","location_class_code","location_number","site_status","corresponding_fixed_location","location_address","location_city","location_county","location_state","radius_of_operation","area_of_operation_code","clearance_indicator","ground_elevation","lat_degrees","lat_minutes","lat_seconds","lat_direction","long_degrees","long_minutes","long_seconds","long_direction","max_lat_degrees","max_lat_minutes","max_lat_seconds","max_lat_direction","max_long_degrees","max_long_minutes","max_long_seconds","max_long_direction","nepa","quiet_zone_notification_date","tower_registration_number","height_of_support_structure","overall_height_of_structure","structure_type","airport_id","location_name","units_hand_held","units_mobile","units_temp_fixed","units_aircraft","units_itinerant","status_code","status_date","earth_agree","calc_latitude","calc_longitude"
LO,2986933,,,WQII545   ,,F,R,4,,,,,,,,,,2340.0,34,2,16.9,N,107,26,46.9,W,,,,,,,,,,,,,,,,NM3MAGDALENA        ,,,,,,,,,34.03802777777778,-107.44636111111112
LO,2986933,,,WQII545   ,,F,R,2,,,,,,,,,,2340.1,34,2,16.8,N,107,26,46.6,W,,,,,,,,,,,,,,,,MAGDALENA           ,,,,,,,,,34.038,-107.44627777777778
LO,2986933,,,WQII545   ,,F,R,3,,,,,,,,,,2326.5,34,18,26.1,N,108,35,41.1,W,,,,,,,,,,,,,,,,NM3 QUEMADO         ,,,,,,,,,34.307249999999996,-108.59474999999999


SELECT receiver_location_number FROM path WHERE unique_system_identifier = 2986933   AND call_sign = 'WQII545' 
"receiver_location_number"
3
4
//----------------------------------------------------------
For a valid entry

SELECT * FROM path WHERE unique_system_identifier = 2986933   AND call_sign = 'WQII545' and receiver_location_number =3  

"record_type","unique_system_identifier","uls_file_number","ebf_number","call_sign","path_action_performed","path_number","transmit_location_number","transmit_antenna_number","receiver_location_number","receiver_antenna_number","mas_dems_subtype","path_type_desc","passive_receiver_indicator","country_code","interference_to_gso","receiver_callsign","angular_sep","cert_no_alternative","cert_no_interference","status_code","status_date","link_start_date","link_end_date"
PA,2986933,,,WQII545   ,,3,1,3,3,2,,Fixed Point-to-Point,N,,N,WQII546,,,,,,,

```
The Path file entry  is needed to  find transmitter details and without which we cannot proceed here.
I am using the ULS data snapshot in the repo `l_micro_211024_modified_PA/LO.dat`

**Comment by AEgbert** [comment]
Thanks for the question. As best as I can tell, receiver location 2 (named "MAGDALENA") is not associated with an active path.

Looking at the [history of the license via the FCC's ULS interface](https://wireless2.fcc.gov/UlsApp/UlsSearch/allApplications.jsp?licKey=2986933), I found [this amendment](https://wireless2.fcc.gov/UlsApp/ApplicationSearch/applMain.jsp?applID=7370543). In the amendment, it appears that locations 1 and 3 were renamed, a new version of location 2 was added (numbered as location 4, named "NM3MAGDALENA"), and paths 1 and 2 (to location 2 and the unmodified location 3) were replaced by paths 3 and 4 (to modified location 3 and the new location 4). Note that the RX call signs for paths 3 and 4 match the RX call signs for the former paths 2 and 1.

In support of location 2 no longer being active, the [amendment purpose](https://wireless2.fcc.gov/UlsEntry/attachments/attachmentViewRD.jsp?applType=search&fileKey=1780157068&attachmentKey=19067190&attachmentInd=applAttach) is "to delete path <span>#</span>1 & 2". This removes the only path associated with location 2 that I am aware of.

**Comment by alexcpn** [comment]
Thanks @AEgbert 
This means that the ULS data snapshot has to be updated and in its present form we cannot use it for AFCS.SIP.3

From what I understood from your clarification is that the entry for Receiver location 2 should be removed/should have been removed ( as the new version of location 2 with Rx location4 and named "NM3MAGDALENA" is added)

LO|2986933|||WQII545||F|R|2||||||||||2340.1|34|2|16.8|N|107|26|46.6|W||||||||||||||||MAGDALENA||||||||

**Comment by AEgbert** [comment]
Updating the snapshot would not impact this case. The record in question has not been modified in the current ULS database since the snapshot was acquired.

My expectation is that locations that are not associated with a path do not need to be protected, as there is no path to protect. I'll reach out for confirmation on this interpretation.

**Comment by AEgbert** [comment]
I received an answer in support of this conclusion. Data integrity issues must be dealt with by the AFC system, and in instances where a location is not associated with a path, there is no way to protect it.

**Comment by alexcpn** [comment]
Thanks @AEgbert ; Can this be mentioned as a note in the documentation

**Comment by AEgbert** [comment]
I'll pass the info along; thanks
