### ISSUE TITLE
Clarification regarding clutter loss

### ISSUE THREAD

**Issue by alexcpn** [Wireless-Innovation-Forum/6-GHz-AFC#54]
I was expanding on the clutter loss calculation part for all conditions and I have some clarification. 

In R2-AIP-15 it is described to handle clutter loss thus

_Clutter loss shall be calculated and applied taking into consideration each morphology separately at the FS receiver antenna and Standard Power Device locations as given in R2-AIP-12.
ii.Clutter loss may be applied at the FS receiver location only if the FS receive antenna height HFS, Rx (AGL) determined as per R2-AIP-14 is lower than 6 meters above ground level._

Regarding the second point, it does not tell about Clutter loss if AP antenna is less than 6 meters, as per the TS 1014 (R2-AGR-05) the minimum height is 1.5 meters

Context is that for Urban and Suburban NLCD codes (ITU-R P.2108-0 (06/2017   https://www.itu.int/dms_pubrec/itu-r/rec/p/R-REC-P.2108-1-202109-I!!PDF-E.pdf)  it talks about the clutter loss calculation only working if height is up to 6 meters. Since this is clearly handled for FS receiver, why is this not needed for AP height < 6 meters

_It is noted that measurements used in the development of this model used terminal heights up to 6 metres above ground._

_R2-AGR-05  Standard Power Device Height Above Ground Level
The AFC System shall assume a height above ground level of 1.5 meters for the Standard Power Device height if the corresponding height reported by the device, HSPD (AGL), is less than 1.5 meters._

@AEgbert

**Comment by AEgbert** [comment]
Per discussions earlier today, the requirements are listed in TS-1014 correctly; the 6 meter requirement is only applied to the FS receiver antenna.

Regarding the statement from P.2108-0 regarding model measurements up to 6 meters, I believe that statement is only present in the subsequent revision P.2108-1, and it is not present in the P.2108-0 revision referenced by TS-1014. Note that P.2108-1 itself does not appear to impose a 6 meter limit, stating that the model can be used at for terminal heights below the clutter height.
