### ISSUE TITLE
NLCD Code in WiNNF repo is  different from US Govt NLCD 2019 data

### ISSUE THREAD

**Issue by alexcpn** [Wireless-Innovation-Forum/6-GHz-AFC#64]
WINNF Repo - https://github.com/Wireless-Innovation-Forum/Common-Data/tree/master/data/nlcd

As per https://github.com/Wireless-Innovation-Forum/Common-Data/blob/694c98ff82b05c5404a8d67698074233456bfae1/data/nlcd/nlcd_n40w122_ref.zip#L2

Light grey Code 52
Darker Grey Code 42
Darkest Grey Code 21
The points shown are the uncertainty points of the Access Point for FSP 71

![image](https://github.com/user-attachments/assets/df30398b-f818-442a-b756-f9d31fcead5b)

Now as per NLCD_2019_Land_Cover 

Green is Code 42
Pink is Code 21

![image](https://github.com/user-attachments/assets/caea6acb-49e7-48cc-a438-a08419a7c2ec)

As we can see the data is too different, and due to this the calculations are not culminating in expected results

**Comment by sergebdt** [comment]
See https://github.com/Wireless-Innovation-Forum/6-GHz-AFC/issues/63#issuecomment-2325759945

**Comment by alexcpn** [comment]
We need to use the latest (2020,2021) landcover from https://www.usgs.gov/centers/eros/science/national-land-cover-database. You will get a file like  `land_cover_2020_30m_tif.zip`, this you can tile using the scripts in https://github.com/Wireless-Innovation-Forum/Common-Data/blob/master/scripts/retile_nlcd.py
