### ISSUE TITLE
109/128 test cases fail after databases from Wi-FiTestSuite are applied

### ISSUE THREAD

**Issue by sambk** [Wireless-Innovation-Forum/6-GHz-AFC#65]
Hi,
According to SUT harness document, I expect that all test cases will pass after I apply all databases from https://github.com/Wi-FiTestSuite/6GHz-AFC on my AFC server system, including:
- ULS Snapshot (converted to .sqlite3)
- NLCD
- 3dep USGS DEM (converted to wgs84)

Unfortunately, the number of failed cases are even more than the latest production database:

> 2024-11-27 23:47:24,608 - Results - DEBUG: Full Test Results:
  Expected results: AFCS.FSP.42, AFCS.FSP.49, AFCS.FSP.57, AFCS.FSP.64, AFCS.FSP.72, AFCS.FSP.74, AFCS.FSP.86, AFCS.FSP.89, AFCS.FSP.93, AFCS.FSP.94, AFCS.IBP.2, AFCS.SRS.1, AFCS.URS.1, AFCS.URS.2, AFCS.URS.3, AFCS.URS.4, AFCS.URS.5, AFCS.URS.6, AFCS.URS.7
Unexpected results: AFCS.FSP.1, AFCS.FSP.10, AFCS.FSP.100, AFCS.FSP.11, AFCS.FSP.12, AFCS.FSP.13, AFCS.FSP.14, AFCS.FSP.15, AFCS.FSP.16, AFCS.FSP.17, AFCS.FSP.18, AFCS.FSP.19, AFCS.FSP.2, AFCS.FSP.20, AFCS.FSP.21, AFCS.FSP.22, AFCS.FSP.23, AFCS.FSP.24, AFCS.FSP.25, AFCS.FSP.26, AFCS.FSP.27, AFCS.FSP.28, AFCS.FSP.29, AFCS.FSP.3, AFCS.FSP.30, AFCS.FSP.31, AFCS.FSP.32, AFCS.FSP.33, AFCS.FSP.34, AFCS.FSP.35, AFCS.FSP.36, AFCS.FSP.37, AFCS.FSP.38, AFCS.FSP.39, AFCS.FSP.4, AFCS.FSP.40, AFCS.FSP.41, AFCS.FSP.43, AFCS.FSP.44, AFCS.FSP.45, AFCS.FSP.46, AFCS.FSP.47, AFCS.FSP.48, AFCS.FSP.5, AFCS.FSP.50, AFCS.FSP.51, AFCS.FSP.52, AFCS.FSP.53, AFCS.FSP.54, AFCS.FSP.55, AFCS.FSP.56, AFCS.FSP.58, AFCS.FSP.59, AFCS.FSP.6, AFCS.FSP.60, AFCS.FSP.61, AFCS.FSP.62, AFCS.FSP.63, AFCS.FSP.65, AFCS.FSP.66, AFCS.FSP.67, AFCS.FSP.68, AFCS.FSP.69, AFCS.FSP.7, AFCS.FSP.70, AFCS.FSP.71, AFCS.FSP.73, AFCS.FSP.75, AFCS.FSP.76, AFCS.FSP.77, AFCS.FSP.78, AFCS.FSP.79, AFCS.FSP.8, AFCS.FSP.80, AFCS.FSP.81, AFCS.FSP.82, AFCS.FSP.83, AFCS.FSP.84, AFCS.FSP.85, AFCS.FSP.87, AFCS.FSP.88, AFCS.FSP.9, AFCS.FSP.90, AFCS.FSP.91, AFCS.FSP.92, AFCS.FSP.95, AFCS.FSP.96, AFCS.FSP.97, AFCS.FSP.98, AFCS.FSP.99, AFCS.IBP.1, AFCS.IBP.3, AFCS.IBP.4, AFCS.SIP.1, AFCS.SIP.10, AFCS.SIP.11, AFCS.SIP.12, AFCS.SIP.13, AFCS.SIP.14, AFCS.SIP.15, AFCS.SIP.16, AFCS.SIP.2, AFCS.SIP.3, AFCS.SIP.4, AFCS.SIP.5, AFCS.SIP.6, AFCS.SIP.7, AFCS.SIP.8, AFCS.SIP.9
     Skipped tests: AFCS.IBP.5, AFCS.IBP.6, AFCS.IBP.7, AFCS.IBP.8
2024-11-27 23:47:24,608 - Results - INFO: Test Summary:
  Expected results: 19
Unexpected results: 109
     Skipped tests: 4

Most of test cases fails because the response values are bigger than the upper threshold (22.9 dBm/MHz for PSD or 36 dBm for EIRP). Looks like the file of ULS .sqlite3 is not very correct.

Could anyone please give me any suggestion? Did I do anything wrong or is my expectation wrong?

Thank you,
Pham Viet Sam

**Comment by AEgbert** [comment]
If an AFC system under test is providing responses beyond the regulated limits (23 dBm/MHz and/or 36dBm EIRP), then the AFC system is not adhering to the necessary regulations. The information within ULS can only provide information on when limits that are more strict than the maximums permitted by regulation should be applied--providing AFC responses beyond the regulated limits is not an issue with the test data (including ULS snapshots) nor the test harness.
