### ISSUE TITLE
How to convert testing ULS data to .sqlite3

### ISSUE THREAD

**Issue by sambk** [Wireless-Innovation-Forum/6-GHz-AFC#67]
Hi teams,
I'm trying to convert ULS data from https://github.com/Wi-FiTestSuite/6GHz-AFC/blob/main/ULS_database/FCC/weekly/l_micro_211024_modified_PA.zip by _daily_uls_parse.py_ script in interactive mode but it does not succeed.

I tried to make the interactive mode run similar to auto mode but It requires a daily folder. However, there is no any daily folder in the testing  data above.

Could anyone help to give some suggestions?

Thank you,
Pham Viet Sam

**Comment by AEgbert** [comment]
I'm not familiar with the `daily_uls_parse.py` script in question. It is not a part of the test harness or data hosted in this repository. I'd recommend referring your question to the author(s) of the `daily_uls_parse.py` script.

For testing purposes, no daily snapshot needs to be applied to the weekly snapshot you referenced. The AFC system under test should utilize the weekly snapshot.
